apiVersion: v1
kind: Service
metadata:
  labels:
    app: bff
  name: bff
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      name: http
  selector:
    app: bff