apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer-api
  name: customer-api
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  selector:
    app: customer-api