apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-api
  name: order-api
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: http
  selector:
    app: order-api